### ISSUE TITLE
Get rid of extra border in toolbar

### ISSUE THREAD

**Issue by dimaip** [psmb/Psmb.FlatNav#21]
Ideally it would be cool to get rid of this extra border:
![image](https://user-images.githubusercontent.com/837032/55405059-edb8a300-5561-11e9-9e32-33079175322a.png)

**Comment by pmaas** [comment]
To achieve this we have to change https://github.com/neos/neos-ui/blob/2.x/packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/index.js#L152, right?

Here is the `border` defined: https://github.com/neos/neos-ui/blob/2.x/packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/style.css#L2

**Comment by dimaip** [comment]
Exactly, just override that border.
