### ISSUE TITLE
Second node with same name is not reachable

### ISSUE THREAD

**Issue by lorenzulrich** [psmb/Psmb.FlatNav#27]
Inside a flat navigation, if you have two nodes with the same name (case-insensitive), you can never change to the second node with the same name. It always jumps back to the first node:

![ezgif-3-3265c86cd29a](https://user-images.githubusercontent.com/1816023/63178506-7a17be00-c04a-11e9-88df-7dae31c593a3.gif)

**Comment by dimaip** [comment]
Took a quick glance at the code, and it doesn't make any sense... The only case where it could happen is if they both had the same `contextPath`...
Anyways, if you figure it out the PRs are welcome!

**Comment by ferdimo** [comment]
It happens regularly because on node creation the uriPathSegment is not checked. Therefore the uriPathSegment of the accessible node has to be modified (e.g. suffixed with -1) in order to be able to access the other node again

**Comment by lorenzulrich** [comment]
This problem has since been solved in Neos.
