### ISSUE TITLE
Item in FlatNav doesn't get active state

### ISSUE THREAD

**Issue by simonschaufi** [psmb/Psmb.FlatNav#31]
Clicking on a node in FlatNav doesn't highlight it as active and it's also not possible to delete it while everything works fine in the tree view.

Neos: 5.1

**Comment by DrillSergeant** [comment]
I can confirm this.

Neos: 5.2.2
UI: 5.2.3
FlatNav: 0.4 and also dev-master (c574d8d468d093fa1a7aedac2e8561fc85bd0504)

**Comment by dimaip** [comment]
Fixed with https://github.com/psmb/Psmb.FlatNav/commit/27acd368d4235f663c1522f77830aa67f0554ddc
