### ISSUE TITLE
Pressing "back" in the node creation allows me to create nodes outside of the configured context

### ISSUE THREAD

**Issue by Sebobo** [psmb/Psmb.FlatNav#6]
How to reproduce:

* Click "Plus" in Flat Nav
* Click "Back" in Dialog
* List of all document types is shown and unclear what would happen if I create a different one.

**Comment by Sebobo** [comment]
In my case it crashes as the options are not valid in the specified path

**Comment by dimaip** [comment]
Sorry, don't get it. What options?

**Comment by Sebobo** [comment]
It allows me to create 3 document types which are valid in other places but not in my Blogfeed page type . There only one nodetype is allowed: "BlogPost".
Therefore when I create a "Shortcut" for example, an error message appears as the constraint complains.

Now you unterstand? :)

**Comment by Sebobo** [comment]
So the expected behavior is that it takes the constraints from the designated parent node instead of wherever it takes it from.

**Comment by dimaip** [comment]
Oh wow, weird, I thought it would use the correct constraints.

**Comment by Sebobo** [comment]
If it would take them you actually might not even need the `newNodeType` setting.

**Comment by dimaip** [comment]
@Sebobo but then it would be an extra click? That's exactly the thing I wanted to avoid.

**Comment by dimaip** [comment]
Can't think of a way to fix it from the extension, other than to re-implement the dialog.

**Comment by dimaip** [comment]
Will close for now until new ideas pop up how to do that.
